# This workflow will run Snyk SAST along with npm audit and FOSSA scans on push and pull request events.

name: SCA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Npm Audit
      run: npm audit
      continue-on-error: true

    - name: Fossa Scan
      uses: fossas/fossa-action@main
      with:
        api-key: ${{secrets.FOSSA_API}}

    - name: Install Snyk
      run: npm install -g snyk snyk-to-html

    - name: Authenticate Snyk
      run: snyk auth "e477db16-122e-4c40-bcee-ef7ab7afacc1"

    - name: Snyk Monitor
      run: snyk monitor --project-name=${{github.repository}}

    - name: Snyk Test and Generate HTML
      run: |
        snyk test --json > snyk_results.json
        snyk-to-html -i snyk_results.json -o snyk_results.html

    - name: Upload Snyk Results
      uses: actions/upload-artifact@v3
      with:
        name: snyk_results
        path: snyk_results.html
