# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: SCA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  NPMaudit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Npm Audit
      run: npm audit --json > npm-audit-results.json
      continue-on-error: true

    - name: Upload NPM Audit Scan Report 
      uses: actions/upload-artifact@v4
      with:
        name: npm-audit-results
        path: npm-audit-results.json

  owasp:
    name: Run OWASP Dependency-Check for Node.js
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Set version of Node.js

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Download OWASP Dependency-Check
      - name: Download OWASP Dependency-Check
        run: |
          curl -L -o dependency-check.tar.gz https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.tar.gz
          tar -xzf dependency-check.tar.gz
          sudo mv dependency-check /usr/local/bin/dependency-check

      # Step 5: Run OWASP Dependency-Check
      - name: Run Dependency-Check for Node.js
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}  # Use secret from GitHub Secrets
        run: |
          /usr/local/bin/dependency-check/bin/dependency-check.sh \
          --project "MyNodeProject" \
          --scan ./ \
          --format "HTML" \
          --out dependency-check-report \
          --cveValidForHours 12 \
          --nvdApiKey $NVD_API_KEY

      # Step 6: Upload report as artifact
      - name: Upload Dependency-Check report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report/